### ISSUE TITLE
Match wildcard certificate

### ISSUE THREAD

**Issue by polcar** [fschulze/check-tls-certs#3]
When I tried to check wildcard certificate I got 

> The requested domain XYZ.domain.com doesn't match the certificate domain *.domain.com.

I could by solve by:

```
import fnmatch
if  not fnmatch.filter([domain.host], name):
```
instead of
```
if name != domain.host:
```

Am I right?

**Comment by fschulze** [comment]
That check is too simple. I added support for wildcard certificates in 0.11.0.
